# Default values for glitchtip.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: registry.gitlab.com/glitchtip/glitchtip-frontend
  tag: master
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
databaseURL:
secretKey:
enableSocialAuth: false

web:
  hpa:
    enabled: false
    cputhreshold: 60
    minpods: 1
    maxpods: 10
  replicaCount: 1
  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 512Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

worker:
  replicaCount: 1
  hpa:
    enabled: false
    cputhreshold: 60
    minpods: 1
    maxpods: 10
  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 256Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

redis:
  enabled: true
  master:
    persistence:
      enabled: false
  slave:
    persistence:
      enabled: false
  cluster:
    enabled: false
    slaveCount: 1

# Default to disabled, use a managed database service. But can be enabled here.
postgresql:
  enabled: false