apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "glitchtip.fullname" . }}
  labels:
    {{- include "glitchtip.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  activeDeadlineSeconds: 60
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: pre-install-job
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["./manage.py","migrate"]
        env:
          - name: DATABASE_URL
          - name: SECRET_KEY
          - name: DEBUG
            value: "False"
          - name: STATIC_URL
            value: /